python train.py \
    --student_model sbintuitions/sarashina2.2-1b \
    --teacher_model Qwen/Qwen2.5-7B-Instruct \
    --data_path data/calm3 \
    --output_dir logs/calm3-taid \
    --batch_size 1 \
    --num_epochs 5 \
    --loss_type taid \
    --taid_t_start 0.4 \
    --taid_alpha 5.e-4 \
    --taid_beta 0.99  