python train.py \
    --student_model TinyLlama/TinyLlama_v1.1 \
    --teacher_model microsoft/Phi-3-mini-4k-instruct \
    --data_path data/phi-3 \
    --output_dir logs/phi-3-taid \
    --batch_size 8 \
    --num_epochs 5 \
    --loss_type taid \
    --taid_t_start 0.4 \
    --taid_alpha 5.e-4 \
    --taid_beta 0.99  